In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.prettify()[:1000])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="tex

In [4]:
books = soup.find_all("article", class_="product_pod")

book_names = []
prices = []
ratings = []

for book in books:
    # Book Name
    name = book.h3.a["title"]
    book_names.append(name)

    # Price
    price = book.find("p", class_="price_color").text
    prices.append(price)

    # Rating
    rating = book.find("p")["class"][1]
    ratings.append(rating)

# Create DataFrame
df = pd.DataFrame({
    "Book Name": book_names,
    "Price": prices,
    "Rating": ratings
})

df.head()

                               Book Name    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [5]:
df.to_csv("scraped_books.csv", index=False)

print("CSV file saved successfully!")

CSV file saved successfully!

In [6]:
# First 5 rows
df.head()

                               Book Name    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [7]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Book Name  20 non-null     object
 1   Price      20 non-null     object
 2   Rating     20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [8]:
# Summary Statistics
df.describe(include="all")

                   Book Name    Price Rating
count                     20       20     20
unique                    20       20      5
top     A Light in the Attic  Â£51.77    One
freq                       1        1      6

In [9]:
# Missing Values
df.isnull().sum()

Book Name    0
Price        0
Rating       0
dtype: int64

In [11]:
df["Price"] = (
    df["Price"]
    .str.replace("Â£", "", regex=False)
    .str.replace("£", "", regex=False)
    .astype(float)
)

df.head()

                               Book Name  Price Rating
0                   A Light in the Attic  51.77  Three
1                     Tipping the Velvet  53.74    One
2                             Soumission  50.10    One
3                          Sharp Objects  47.82   Four
4  Sapiens: A Brief History of Humankind  54.23   Five

In [12]:
most_expensive = df.loc[df["Price"].idxmax()]

print("Most Expensive Book:")
print(most_expensive)

Most Expensive Book:
Book Name    Our Band Could Be Your Life: Scenes from the A...
Price                                                    57.25
Rating                                                   Three
Name: 15, dtype: object

In [13]:
cheapest = df.loc[df["Price"].idxmin()]

print("Cheapest Book:")
print(cheapest)

Cheapest Book:
Book Name    Starving Hearts (Triangular Trade Trilogy, #1)
Price                                                 13.99
Rating                                                  Two
Name: 10, dtype: object

In [14]:
print(df["Rating"].value_counts())

Rating
One      6
Five     4
Four     4
Three    3
Two      3
Name: count, dtype: int64

Project Conclusion

• Successfully scraped book data from a public website using BeautifulSoup.
• Extracted Book Name, Price, and Rating.
• Created a custom dataset and saved it as CSV.
• Cleaned the scraped data.
• Performed exploratory data analysis.
• Visualized rating and price distributions using Matplotlib.

This project demonstrates practical skills in Web Scraping, HTML Parsing, Data Cleaning, Data Analysis, and Data Visualization using Python.